<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prasanna" failures="1" tests="3" name="com.zenken.freshers.user.FieldOfStudy" time="40.993" errors="0" timestamp="2024-11-12T15:06:08 IST" skipped="2">
  <testcase classname="com.zenken.freshers.user.FieldOfStudy" name="verifyITOptionSelection" time="14.542">
    <failure message="Area of research is incorrect expected [ITa] but found [IT]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Area of research is incorrect expected [ITa] but found [IT]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection(FieldOfStudy.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifyITOptionSelection -->
  <testcase classname="com.zenken.freshers.user.FieldOfStudy" name="verifyITOptionSelection" time="12.723">
    <skipped/>
  </testcase> <!-- verifyITOptionSelection -->
  <testcase classname="com.zenken.freshers.user.FieldOfStudy" name="verifyITOptionSelection" time="13.728">
    <skipped/>
  </testcase> <!-- verifyITOptionSelection -->
</testsuite> <!-- com.zenken.freshers.user.FieldOfStudy -->
